### ISSUE TITLE
Resource missing flow-jvm-sdk/0.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by b-fab-michael** [onflow/flow-java-client-example#10]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/org/onflow/flow-jvm-sdk/0.2.0-SNAPSHOT/maven-metadata.xml]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/org/onflow/flow-jvm-sdk/0.2.0-SNAPSHOT/flow-jvm-sdk-0.2.0-SNAPSHOT.pom]
Resource missing. [HTTP GET: https://jitpack.io/org/onflow/flow-jvm-sdk/0.2.0-SNAPSHOT/maven-metadata.xml]
       - https://plugins.gradle.org/m2/org/onflow/flow-jvm-sdk/0.2.0-SNAPSHOT/maven-metadata.xml
       - https://plugins.gradle.org/m2/org/onflow/flow-jvm-sdk/0.2.0-SNAPSHOT/flow-jvm-sdk-0.2.0-SNAPSHOT.pom
       - https://repo1.maven.org/maven2/org/onflow/flow-jvm-sdk/0.2.0-SNAPSHOT/maven-metadata.xml
       - https://repo1.maven.org/maven2/org/onflow/flow-jvm-sdk/0.2.0-SNAPSHOT/flow-jvm-sdk-0.2.0-SNAPSHOT.pom

issue:  Where  maven is " flow-jvm-sdk/0.2.0-SNAPSHOT  " in ?

**Comment by lealobanov** [comment]
<img width="1428" alt="Screenshot 2024-02-14 at 17 54 22" src="https://github.com/onflow/flow-java-client-example/assets/44328396/7d437b4c-3f4b-4c98-a707-19de12b79bff">

Hi @b-fab-michael, just checked Maven Central for past releases of the SDK: https://central.sonatype.com/artifact/com.nftco/flow-jvm-sdk/versions. Looks like the first release was for v0.2.1 (0.2.0 does not exist). As bug fixes have been released in subsequent versions, we recommend using the latest release - currently v0.7.4.

Thanks!
