### ISSUE TITLE
Move these examples to the flow-jvm-sdk project

### ISSUE THREAD

**Issue by briandilley** [onflow/flow-java-client-example#2]
While updating this project for the latest version of the [flow-jvm-sdk](https://github.com/onflow/flow-jvm-sdk) I realized that there were some changes necessary to the SDK itself. It would make it much easier to keep these examples up to date if we added them to the the SDK project itself. We could update the SDK project to be a multi-module project with 3 modules: sdk, java-example, kotlin-example. @psiemens @m4ksio thoughts?

**Comment by m4ksio** [comment]
the idea was that this project can serve as a template for people wanting to connect to Flow. Also, keeping them separate helps us catch incompatible changes - therefor I would vote for no, but happy to hear @psiemens opinion

**Comment by lealobanov** [comment]
This issue has now been closed as part of https://github.com/onflow/flow-jvm-sdk/pull/62
