### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by TracyH1988** [onflow/flow-java-client-example#6]
what does this mean?
![image](https://user-images.githubusercontent.com/13996290/144741439-8b19f0e1-4dba-4ca3-af53-b116151bfd83.png)

the problems are here mybe, but how to fix it?.
![微信图片_20211205174701](https://user-images.githubusercontent.com/13996290/144741561-dc9039fa-1922-4ecc-8157-7a2a9eea075c.png)

**Comment by bluesign** [comment]
if you are signing envelope, you shouldn't sign the payload. 

So if payer is authorizer, only signs envelope.

**Comment by TracyH1988** [comment]
> if you are signing envelope, you shouldn't sign the payload.
> 
> So if payer is authorizer, only signs envelope.

thanks  , it works

**Comment by TracyH1988** [comment]
> if you are signing envelope, you shouldn't sign the payload.
> 
> So if payer is authorizer, only signs envelope.



> > if you are signing envelope, you shouldn't sign the payload.
> > So if payer is authorizer, only signs envelope.
> 
> thanks , it works

**Comment by TracyH1988** [comment]
> if you are signing envelope, you shouldn't sign the payload.
> 
> So if payer is authorizer, only signs envelope.

another issue,
   when I test in mainnet
I got null return for createaccount:
![image](https://user-images.githubusercontent.com/13996290/144743183-e0987c88-3a42-4d98-ae61-fdd2105674a7.png)
![image](https://user-images.githubusercontent.com/13996290/144743215-17fa7aa0-6caf-45ad-8dfa-ba4e4a60dcde.png)
![image](https://user-images.githubusercontent.com/13996290/144743256-a9104692-44ae-4adb-9731-b3f767cb6d9a.png)
